name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} cargo build --verbose
    - name: Run tests
      run: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} cargo test --verbose
