on: push

jobs:
  build_cache:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/cache_cargo

      - name: build
        run: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} cargo build

  fmt:
    runs-on: ubuntu-latest

    needs: build_cache

    steps:
      - uses: actions/checkout@v2

      - run: rustup component add rustfmt

      - uses: ./.github/actions/cache_cargo

      - name: fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    needs: build_cache

    steps:
      - uses: actions/checkout@v2

      - run: rustup component add clippy

      - uses: ./.github/actions/cache_cargo

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings